export { default as Main } from "./Main";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Story } from "./StoryBlock";
export { default as Features } from "./Features";
// export { default as Quote } from "./QuoteBlock";
export { default as Distribution } from "./Distribution";
export { default as Token } from "./Token";
export { default as Steps } from "./Steps";
export { default as Tokenomics } from "./Tokenomics";
export { default as Why } from "./Why";
export { default as GoldCatBlock } from "./GoldCatBlock";
export { default as Footer } from "./Footer";
export { default as Preloader } from "./Preloader";
